services:
  - type: web
    name: taskflow-server
    runtime: node
    buildCommand: npm install && npm run build --workspace=server
    startCommand: cd server && npm run start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_OAUTH_CLIENT_ID
        sync: false
      - key: GITHUB_OAUTH_CLIENT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BASE_URL
        sync: false
      - key: PORT
        value: 4000
